### ISSUE TITLE
Update AixLib

### ISSUE THREAD

**Issue by PRemmen** [EnEff-BIM/EnEffBIM_UseCases#2]
For stability reasons it would make sense to update the AixLib UseCases to a more up to date version. This shouldnt't affect the Use Case or the results

**Comment by thorade** [comment]
Tested it and it works

**Comment by ReinhardWimmer** [comment]
I wil update the mapping table. We should do the same for all the other use cases. I have a student @tobiasquack working with the mapping tables, just let us know when the use cases are up to date and we can create the final versions for the mapping tables. But one thing I want to point out: I hope that is the last update of the use cases, referring to the mapping tables, otherwise it will be a neverending story ;)
Anyway, I start working here in Berkeley on the Use Case 5.0 (BIG boy), at the end, this will be the example we should present, because this use case represents a more realisitc example, compared to that single room use cases.
